services:
  app:
    build:
      context: ./infra/php/
      # context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    platform: linux/arm64/v8
    volumes:
      - ./src:/work
      - ./infra/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      - XDEBUG_CONFIG="client_host=host.docker.internal"
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_DATABASE:-app}
      - DB_USERNAME=${MYSQL_USER:-phper}
      - DB_PASSWORD=${MYSQL_PASSWORD:-secret}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9005:9005"
    depends_on:
      - db
      - redis
      - mailhog
    networks:
      - laravel_network

  # Nginx Webサーバー
  web:
    image: nginx:1.26-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
    depends_on:
      - app
    networks:
      - laravel_network

  # MySQLデータベース
  db:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-phper}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./infra/mysql/init:/docker-entrypoint-initdb.d
    command: --local-infile=1
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  # Redisキャッシュサーバー
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server
    networks:
      - laravel_network

  # メールサーバー（開発用）
  mailhog:
    image: axllent/mailpit
    ports:
      - 8025:8025 # Web UI用
      - 1025:1025 # SMTPサーバー用
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
